import type { Tool, ToolContext, PluginContext, ToolCallResult } from "cortex/plugins";

let config: Record<string, string | boolean> = {};

export async function onLoad(ctx: PluginContext): Promise<void> {
  config = {
    defaultTool: (await ctx.config.get("defaultTool")) ?? "terraform",
    defaultProvider: (await ctx.config.get("defaultProvider")) ?? "aws",
    requireApproval: (await ctx.config.get("requireApproval")) ?? true,
  };
}

export async function onUnload(_ctx: PluginContext): Promise<void> {}

async function runShell(cmd: string, args: string[], cwd?: string): Promise<{ success: boolean; stdout: string; stderr: string }> {
  const p = new Deno.Command(cmd, { args, cwd: cwd || undefined });
  const { stdout, stderr } = await p.output();
  return {
    success: p.spawn().status !== null,
    stdout: new TextDecoder().decode(stdout),
    stderr: new TextDecoder().decode(stderr),
  };
}

function resolveTool(tool: string): { cmd: string; ext: string } {
  if (tool === "pulumi") return { cmd: "pulumi", ext: ".ts" };
  return { cmd: "terraform", ext: ".tf" };
}

const iac_generate: Tool = {
  definition: {
    name: "iac_generate",
    description: "Generate IaC from description",
    params: [
      { name: "description", type: "string", description: "Natural language description of infrastructure", required: true },
      { name: "tool", type: "string", description: "IaC tool: terraform or pulumi", required: false },
      { name: "provider", type: "string", description: "Cloud provider", required: false },
      { name: "output_file", type: "string", description: "Output file path", required: true },
    ],
    capabilities: ["fs:write", "shell:run"],
  },
  execute: async (args: Record<string, unknown>, _ctx: ToolContext): Promise<ToolCallResult> => {
    const start = Date.now();
    try {
      const description = args.description as string;
      const outputFile = args.output_file as string;
      if (!description || !outputFile) {
        return { toolName: "iac_generate", success: false, output: "", error: "description and output_file are required", durationMs: Date.now() - start };
      }
      const tool = (args.tool as string) ?? config.defaultTool ?? "terraform";
      const provider = (args.provider as string) ?? config.defaultProvider ?? "aws";
      const { ext } = resolveTool(tool);

      const filePath = outputFile.endsWith(ext) ? outputFile : `${outputFile}${ext}`;
      const header = tool === "pulumi"
        ? `// Generated by CortexPrism IaC Plugin\n// Provider: ${provider}\n// Description: ${description}\n\nimport * as pulumi from "@pulumi/pulumi";\nimport * as ${provider} from "@pulumi/${provider}";\n\n`
        : `# Generated by CortexPrism IaC Plugin\n# Provider: ${provider}\n# Description: ${description}\n\nterraform {\n  required_providers {\n    ${provider} = {\n      source = "hashicorp/${provider}"\n    }\n  }\n}\n\n`;

      await Deno.writeTextFile(filePath, header);
      return { toolName: "iac_generate", success: true, output: `IaC scaffold written to ${filePath}`, durationMs: Date.now() - start };
    } catch (error) {
      return { toolName: "iac_generate", success: false, output: "", error: `Failed to generate IaC: ${error instanceof Error ? error.message : String(error)}`, durationMs: Date.now() - start };
    }
  },
};

const iac_validate: Tool = {
  definition: {
    name: "iac_validate",
    description: "Validate IaC configuration",
    params: [
      { name: "path", type: "string", description: "Path to IaC files", required: true },
      { name: "tool", type: "string", description: "IaC tool: terraform or pulumi", required: false },
    ],
    capabilities: ["shell:run"],
  },
  execute: async (args: Record<string, unknown>, _ctx: ToolContext): Promise<ToolCallResult> => {
    const start = Date.now();
    try {
      const path = args.path as string;
      if (!path) {
        return { toolName: "iac_validate", success: false, output: "", error: "path is required", durationMs: Date.now() - start };
      }
      const tool = (args.tool as string) ?? config.defaultTool ?? "terraform";
      const { cmd } = resolveTool(tool);
      const validateArgs = tool === "pulumi" ? ["preview", "--diff"] : ["validate"];
      const p = new Deno.Command(cmd, { args: validateArgs, cwd: path });
      const { stdout, stderr } = await p.output();
      const output = new TextDecoder().decode(stdout);
      const err = new TextDecoder().decode(stderr);
      if (err && !err.includes("Success")) {
        return { toolName: "iac_validate", success: false, output, error: err, durationMs: Date.now() - start };
      }
      return { toolName: "iac_validate", success: true, output: output || `Configuration for ${tool} is valid`, durationMs: Date.now() - start };
    } catch (error) {
      return { toolName: "iac_validate", success: false, output: "", error: `Failed to validate: ${error instanceof Error ? error.message : String(error)}`, durationMs: Date.now() - start };
    }
  },
};

const iac_plan: Tool = {
  definition: {
    name: "iac_plan",
    description: "Run plan/preview",
    params: [
      { name: "path", type: "string", description: "Path to IaC files", required: true },
      { name: "tool", type: "string", description: "IaC tool: terraform or pulumi", required: false },
    ],
    capabilities: ["shell:run"],
  },
  execute: async (args: Record<string, unknown>, _ctx: ToolContext): Promise<ToolCallResult> => {
    const start = Date.now();
    try {
      const path = args.path as string;
      if (!path) {
        return { toolName: "iac_plan", success: false, output: "", error: "path is required", durationMs: Date.now() - start };
      }
      const tool = (args.tool as string) ?? config.defaultTool ?? "terraform";
      const { cmd } = resolveTool(tool);
      const planArgs = tool === "pulumi" ? ["preview"] : ["plan"];
      const p = new Deno.Command(cmd, { args: planArgs, cwd: path });
      const { stdout, stderr } = await p.output();
      const output = new TextDecoder().decode(stdout);
      const err = new TextDecoder().decode(stderr);
      return { toolName: "iac_plan", success: true, output: output || err, durationMs: Date.now() - start };
    } catch (error) {
      return { toolName: "iac_plan", success: false, output: "", error: `Failed to plan: ${error instanceof Error ? error.message : String(error)}`, durationMs: Date.now() - start };
    }
  },
};

const iac_apply: Tool = {
  definition: {
    name: "iac_apply",
    description: "Apply changes (requires approval)",
    params: [
      { name: "path", type: "string", description: "Path to IaC files", required: true },
      { name: "tool", type: "string", description: "IaC tool: terraform or pulumi", required: false },
      { name: "auto_approve", type: "boolean", description: "Skip approval prompt", required: false },
    ],
    capabilities: ["shell:run"],
  },
  execute: async (args: Record<string, unknown>, _ctx: ToolContext): Promise<ToolCallResult> => {
    const start = Date.now();
    try {
      const path = args.path as string;
      if (!path) {
        return { toolName: "iac_apply", success: false, output: "", error: "path is required", durationMs: Date.now() - start };
      }
      const tool = (args.tool as string) ?? config.defaultTool ?? "terraform";
      const autoApprove = args.auto_approve ?? false;
      if (config.requireApproval && !autoApprove) {
        return { toolName: "iac_apply", success: false, output: "", error: "Approval required. Set auto_approve=true or disable requireApproval in config.", durationMs: Date.now() - start };
      }

      const { cmd } = resolveTool(tool);
      const applyArgs = tool === "pulumi" ? ["up", "--yes"] : ["apply", "-auto-approve"];
      const p = new Deno.Command(cmd, { args: applyArgs, cwd: path });
      const { stdout, stderr } = await p.output();
      const output = new TextDecoder().decode(stdout);
      const err = new TextDecoder().decode(stderr);
      return { toolName: "iac_apply", success: true, output: output || err || "Apply completed", durationMs: Date.now() - start };
    } catch (error) {
      return { toolName: "iac_apply", success: false, output: "", error: `Failed to apply: ${error instanceof Error ? error.message : String(error)}`, durationMs: Date.now() - start };
    }
  },
};

const iac_destroy: Tool = {
  definition: {
    name: "iac_destroy",
    description: "Destroy infrastructure",
    params: [
      { name: "path", type: "string", description: "Path to IaC files", required: true },
      { name: "tool", type: "string", description: "IaC tool: terraform or pulumi", required: false },
      { name: "force", type: "boolean", description: "Force destroy without confirmation", required: false },
    ],
    capabilities: ["shell:run"],
  },
  execute: async (args: Record<string, unknown>, _ctx: ToolContext): Promise<ToolCallResult> => {
    const start = Date.now();
    try {
      const path = args.path as string;
      if (!path) {
        return { toolName: "iac_destroy", success: false, output: "", error: "path is required", durationMs: Date.now() - start };
      }
      const tool = (args.tool as string) ?? config.defaultTool ?? "terraform";
      const force = args.force ?? false;
      if (!force) {
        return { toolName: "iac_destroy", success: false, output: "", error: "Destroy requires confirmation. Set force=true to proceed.", durationMs: Date.now() - start };
      }

      const { cmd } = resolveTool(tool);
      const destroyArgs = tool === "pulumi" ? ["destroy", "--yes"] : ["destroy", "-auto-approve"];
      const p = new Deno.Command(cmd, { args: destroyArgs, cwd: path });
      const { stdout, stderr } = await p.output();
      const output = new TextDecoder().decode(stdout);
      const err = new TextDecoder().decode(stderr);
      return { toolName: "iac_destroy", success: true, output: output || err || "Destroy completed", durationMs: Date.now() - start };
    } catch (error) {
      return { toolName: "iac_destroy", success: false, output: "", error: `Failed to destroy: ${error instanceof Error ? error.message : String(error)}`, durationMs: Date.now() - start };
    }
  },
};

export const tools: Tool[] = [iac_generate, iac_validate, iac_plan, iac_apply, iac_destroy];
